/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Month = IDL.Nat;
export const Year = IDL.Nat;
export const GoalType = IDL.Variant({
  'habit' : IDL.Null,
  'custom' : IDL.Text,
  'monthly' : IDL.Null,
  'yearly' : IDL.Null,
  'daily' : IDL.Null,
  'project' : IDL.Null,
  'weekly' : IDL.Null,
});
export const ActivityId = IDL.Nat;
export const Activity = IDL.Record({
  'startTime' : IDL.Opt(IDL.Text),
  'duration' : IDL.Opt(IDL.Nat),
  'endTime' : IDL.Opt(IDL.Text),
  'goalType' : GoalType,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'recurring' : IDL.Bool,
  'activityId' : ActivityId,
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'coverImage' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'colorHex' : IDL.Opt(IDL.Text),
});
export const FinanceType = IDL.Variant({
  'expense' : IDL.Null,
  'investment' : IDL.Null,
  'income' : IDL.Null,
});
export const FinanceId = IDL.Nat;
export const Finance = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'recurring' : IDL.Bool,
  'financeType' : FinanceType,
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'updatedAt' : IDL.Int,
  'financeId' : FinanceId,
  'amount' : IDL.Nat,
  'purpose' : IDL.Text,
});
export const HabitId = IDL.Nat;
export const Habit = IDL.Record({
  'isCompleted' : IDL.Bool,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'habitId' : HabitId,
  'author' : IDL.Principal,
  'updatedAt' : IDL.Int,
});
export const JournalId = IDL.Nat;
export const JournalAccessType = IDL.Variant({
  'public_journal_access' : IDL.Null,
  'private_journal_access' : IDL.Null,
});
export const Journal = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'journalId' : JournalId,
  'locked' : IDL.Bool,
  'accessType' : JournalAccessType,
  'author' : IDL.Principal,
  'sharedWith' : IDL.Opt(IDL.Vec(IDL.Text)),
  'entropy' : IDL.Nat,
  'coverImage' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'colorHex' : IDL.Opt(IDL.Text),
  'hasAttachments' : IDL.Bool,
});
export const ReminderId = IDL.Nat;
export const Reminder = IDL.Record({
  'reminderId' : ReminderId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'repeatSchema' : IDL.Opt(IDL.Text),
  'author' : IDL.Principal,
  'updatedAt' : IDL.Int,
  'colorHex' : IDL.Opt(IDL.Text),
  'targetDate' : IDL.Text,
});
export const Theme = IDL.Variant({
  'red' : IDL.Null,
  'custom' : IDL.Text,
  'blue' : IDL.Null,
  'dark' : IDL.Null,
  'purple' : IDL.Null,
  'light' : IDL.Null,
  'green' : IDL.Null,
  'yellow' : IDL.Null,
});
export const Language = IDL.Variant({
  'custom' : IDL.Text,
  'portuguese' : IDL.Null,
  'japanese' : IDL.Null,
  'chinese' : IDL.Null,
  'italian' : IDL.Null,
  'spanish' : IDL.Null,
  'german' : IDL.Null,
  'arabic' : IDL.Null,
  'french' : IDL.Null,
  'russian' : IDL.Null,
  'dutch' : IDL.Null,
  'english' : IDL.Null,
  'korean' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'theme' : Theme,
  'username' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Opt(IDL.Text),
  'language' : Language,
  'updatedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calendar' : IDL.Func([Month, Year], [IDL.Text], ['query']),
  'care' : IDL.Func([], [IDL.Bool], ['query']),
  'createActivity' : IDL.Func([Activity], [ActivityId], []),
  'createFinance' : IDL.Func([Finance], [FinanceId], []),
  'createHabit' : IDL.Func([Habit], [HabitId], []),
  'createJournal' : IDL.Func([Journal], [JournalId], []),
  'createReminder' : IDL.Func([Reminder], [ReminderId], []),
  'deleteActivity' : IDL.Func([ActivityId], [], []),
  'deleteFinance' : IDL.Func([FinanceId], [], []),
  'deleteHabit' : IDL.Func([HabitId], [], []),
  'deleteJournal' : IDL.Func([JournalId], [], []),
  'deleteReminder' : IDL.Func([ReminderId], [], []),
  'getActivitiesByDate' : IDL.Func([IDL.Text], [IDL.Vec(Activity)], ['query']),
  'getActivitiesForDates' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Text, IDL.Vec(Activity)],
      ['query'],
    ),
  'getActivity' : IDL.Func([ActivityId], [Activity], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFinancesByDate' : IDL.Func([IDL.Text], [IDL.Vec(Finance)], ['query']),
  'getFinancesForDates' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Text, IDL.Vec(Finance)],
      ['query'],
    ),
  'getHabitsByDate' : IDL.Func([IDL.Text], [IDL.Vec(Habit)], ['query']),
  'getHabitsForDates' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Text, IDL.Vec(Habit)],
      ['query'],
    ),
  'getJournalByDate' : IDL.Func([IDL.Text], [IDL.Opt(Journal)], ['query']),
  'getJournalsForDates' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Text, IDL.Vec(Journal)],
      ['query'],
    ),
  'getRemindersByDate' : IDL.Func([IDL.Text], [IDL.Vec(Reminder)], ['query']),
  'getRemindersForDates' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Text, IDL.Vec(Reminder)],
      ['query'],
    ),
  'getSetupStatus' : IDL.Func([], [IDL.Bool], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [UserProfile], []),
  'updateActivity' : IDL.Func([ActivityId, Activity], [], []),
  'updateHabit' : IDL.Func([HabitId, Habit], [], []),
  'updateJournal' : IDL.Func([JournalId, Journal], [], []),
  'week' : IDL.Func([], [IDL.Vec(IDL.Text), IDL.Bool, IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Month = IDL.Nat;
  const Year = IDL.Nat;
  const GoalType = IDL.Variant({
    'habit' : IDL.Null,
    'custom' : IDL.Text,
    'monthly' : IDL.Null,
    'yearly' : IDL.Null,
    'daily' : IDL.Null,
    'project' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const ActivityId = IDL.Nat;
  const Activity = IDL.Record({
    'startTime' : IDL.Opt(IDL.Text),
    'duration' : IDL.Opt(IDL.Nat),
    'endTime' : IDL.Opt(IDL.Text),
    'goalType' : GoalType,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'recurring' : IDL.Bool,
    'activityId' : ActivityId,
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'coverImage' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'colorHex' : IDL.Opt(IDL.Text),
  });
  const FinanceType = IDL.Variant({
    'expense' : IDL.Null,
    'investment' : IDL.Null,
    'income' : IDL.Null,
  });
  const FinanceId = IDL.Nat;
  const Finance = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'recurring' : IDL.Bool,
    'financeType' : FinanceType,
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'updatedAt' : IDL.Int,
    'financeId' : FinanceId,
    'amount' : IDL.Nat,
    'purpose' : IDL.Text,
  });
  const HabitId = IDL.Nat;
  const Habit = IDL.Record({
    'isCompleted' : IDL.Bool,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'habitId' : HabitId,
    'author' : IDL.Principal,
    'updatedAt' : IDL.Int,
  });
  const JournalId = IDL.Nat;
  const JournalAccessType = IDL.Variant({
    'public_journal_access' : IDL.Null,
    'private_journal_access' : IDL.Null,
  });
  const Journal = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'journalId' : JournalId,
    'locked' : IDL.Bool,
    'accessType' : JournalAccessType,
    'author' : IDL.Principal,
    'sharedWith' : IDL.Opt(IDL.Vec(IDL.Text)),
    'entropy' : IDL.Nat,
    'coverImage' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'colorHex' : IDL.Opt(IDL.Text),
    'hasAttachments' : IDL.Bool,
  });
  const ReminderId = IDL.Nat;
  const Reminder = IDL.Record({
    'reminderId' : ReminderId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'repeatSchema' : IDL.Opt(IDL.Text),
    'author' : IDL.Principal,
    'updatedAt' : IDL.Int,
    'colorHex' : IDL.Opt(IDL.Text),
    'targetDate' : IDL.Text,
  });
  const Theme = IDL.Variant({
    'red' : IDL.Null,
    'custom' : IDL.Text,
    'blue' : IDL.Null,
    'dark' : IDL.Null,
    'purple' : IDL.Null,
    'light' : IDL.Null,
    'green' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const Language = IDL.Variant({
    'custom' : IDL.Text,
    'portuguese' : IDL.Null,
    'japanese' : IDL.Null,
    'chinese' : IDL.Null,
    'italian' : IDL.Null,
    'spanish' : IDL.Null,
    'german' : IDL.Null,
    'arabic' : IDL.Null,
    'french' : IDL.Null,
    'russian' : IDL.Null,
    'dutch' : IDL.Null,
    'english' : IDL.Null,
    'korean' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'theme' : Theme,
    'username' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Opt(IDL.Text),
    'language' : Language,
    'updatedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calendar' : IDL.Func([Month, Year], [IDL.Text], ['query']),
    'care' : IDL.Func([], [IDL.Bool], ['query']),
    'createActivity' : IDL.Func([Activity], [ActivityId], []),
    'createFinance' : IDL.Func([Finance], [FinanceId], []),
    'createHabit' : IDL.Func([Habit], [HabitId], []),
    'createJournal' : IDL.Func([Journal], [JournalId], []),
    'createReminder' : IDL.Func([Reminder], [ReminderId], []),
    'deleteActivity' : IDL.Func([ActivityId], [], []),
    'deleteFinance' : IDL.Func([FinanceId], [], []),
    'deleteHabit' : IDL.Func([HabitId], [], []),
    'deleteJournal' : IDL.Func([JournalId], [], []),
    'deleteReminder' : IDL.Func([ReminderId], [], []),
    'getActivitiesByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'getActivitiesForDates' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Text, IDL.Vec(Activity)],
        ['query'],
      ),
    'getActivity' : IDL.Func([ActivityId], [Activity], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFinancesByDate' : IDL.Func([IDL.Text], [IDL.Vec(Finance)], ['query']),
    'getFinancesForDates' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Text, IDL.Vec(Finance)],
        ['query'],
      ),
    'getHabitsByDate' : IDL.Func([IDL.Text], [IDL.Vec(Habit)], ['query']),
    'getHabitsForDates' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Text, IDL.Vec(Habit)],
        ['query'],
      ),
    'getJournalByDate' : IDL.Func([IDL.Text], [IDL.Opt(Journal)], ['query']),
    'getJournalsForDates' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Text, IDL.Vec(Journal)],
        ['query'],
      ),
    'getRemindersByDate' : IDL.Func([IDL.Text], [IDL.Vec(Reminder)], ['query']),
    'getRemindersForDates' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Text, IDL.Vec(Reminder)],
        ['query'],
      ),
    'getSetupStatus' : IDL.Func([], [IDL.Bool], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [UserProfile], []),
    'updateActivity' : IDL.Func([ActivityId, Activity], [], []),
    'updateHabit' : IDL.Func([HabitId, Habit], [], []),
    'updateJournal' : IDL.Func([JournalId, Journal], [], []),
    'week' : IDL.Func([], [IDL.Vec(IDL.Text), IDL.Bool, IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };