/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'startTime' : [] | [string],
  'duration' : [] | [bigint],
  'endTime' : [] | [string],
  'goalType' : GoalType,
  'date' : string,
  'name' : string,
  'createdAt' : bigint,
  'recurring' : boolean,
  'activityId' : ActivityId,
  'description' : string,
  'author' : Principal,
  'coverImage' : [] | [string],
  'updatedAt' : bigint,
  'colorHex' : [] | [string],
}
export type ActivityId = bigint;
export interface Finance {
  'title' : string,
  'date' : string,
  'createdAt' : bigint,
  'recurring' : boolean,
  'financeType' : FinanceType,
  'description' : string,
  'author' : Principal,
  'updatedAt' : bigint,
  'financeId' : FinanceId,
  'amount' : bigint,
  'purpose' : string,
}
export type FinanceId = bigint;
export type FinanceType = { 'expense' : null } |
  { 'investment' : null } |
  { 'income' : null };
export type GoalType = { 'habit' : null } |
  { 'custom' : string } |
  { 'monthly' : null } |
  { 'yearly' : null } |
  { 'daily' : null } |
  { 'project' : null } |
  { 'weekly' : null };
export interface Habit {
  'isCompleted' : boolean,
  'date' : string,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'habitId' : HabitId,
  'author' : Principal,
  'updatedAt' : bigint,
}
export type HabitId = bigint;
export interface Journal {
  'title' : string,
  'content' : string,
  'date' : string,
  'createdAt' : bigint,
  'journalId' : JournalId,
  'locked' : boolean,
  'accessType' : JournalAccessType,
  'author' : Principal,
  'sharedWith' : [] | [Array<string>],
  'entropy' : bigint,
  'coverImage' : [] | [string],
  'updatedAt' : bigint,
  'colorHex' : [] | [string],
  'hasAttachments' : boolean,
}
export type JournalAccessType = { 'public_journal_access' : null } |
  { 'private_journal_access' : null };
export type JournalId = bigint;
export type Language = { 'custom' : string } |
  { 'portuguese' : null } |
  { 'japanese' : null } |
  { 'chinese' : null } |
  { 'italian' : null } |
  { 'spanish' : null } |
  { 'german' : null } |
  { 'arabic' : null } |
  { 'french' : null } |
  { 'russian' : null } |
  { 'dutch' : null } |
  { 'english' : null } |
  { 'korean' : null };
export type Month = bigint;
export interface Reminder {
  'reminderId' : ReminderId,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'repeatSchema' : [] | [string],
  'author' : Principal,
  'updatedAt' : bigint,
  'colorHex' : [] | [string],
  'targetDate' : string,
}
export type ReminderId = bigint;
export type Theme = { 'red' : null } |
  { 'custom' : string } |
  { 'blue' : null } |
  { 'dark' : null } |
  { 'purple' : null } |
  { 'light' : null } |
  { 'green' : null } |
  { 'yellow' : null };
export interface UserProfile {
  'theme' : Theme,
  'username' : string,
  'createdAt' : bigint,
  'email' : [] | [string],
  'language' : Language,
  'updatedAt' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Year = bigint;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calendar' : ActorMethod<[Month, Year], string>,
  'care' : ActorMethod<[], boolean>,
  'createActivity' : ActorMethod<[Activity], ActivityId>,
  'createFinance' : ActorMethod<[Finance], FinanceId>,
  'createHabit' : ActorMethod<[Habit], HabitId>,
  'createJournal' : ActorMethod<[Journal], JournalId>,
  'createReminder' : ActorMethod<[Reminder], ReminderId>,
  'deleteActivity' : ActorMethod<[ActivityId], undefined>,
  'deleteFinance' : ActorMethod<[FinanceId], undefined>,
  'deleteHabit' : ActorMethod<[HabitId], undefined>,
  'deleteJournal' : ActorMethod<[JournalId], undefined>,
  'deleteReminder' : ActorMethod<[ReminderId], undefined>,
  'getActivitiesByDate' : ActorMethod<[string], Array<Activity>>,
  'getActivitiesForDates' : ActorMethod<
    [Array<string>],
    [string, Array<Activity>]
  >,
  'getActivity' : ActorMethod<[ActivityId], Activity>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFinancesByDate' : ActorMethod<[string], Array<Finance>>,
  'getFinancesForDates' : ActorMethod<
    [Array<string>],
    [string, Array<Finance>]
  >,
  'getHabitsByDate' : ActorMethod<[string], Array<Habit>>,
  'getHabitsForDates' : ActorMethod<[Array<string>], [string, Array<Habit>]>,
  'getJournalByDate' : ActorMethod<[string], [] | [Journal]>,
  'getJournalsForDates' : ActorMethod<
    [Array<string>],
    [string, Array<Journal>]
  >,
  'getRemindersByDate' : ActorMethod<[string], Array<Reminder>>,
  'getRemindersForDates' : ActorMethod<
    [Array<string>],
    [string, Array<Reminder>]
  >,
  'getSetupStatus' : ActorMethod<[], boolean>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], UserProfile>,
  'updateActivity' : ActorMethod<[ActivityId, Activity], undefined>,
  'updateHabit' : ActorMethod<[HabitId, Habit], undefined>,
  'updateJournal' : ActorMethod<[JournalId, Journal], undefined>,
  'week' : ActorMethod<[], [Array<string>, boolean, string]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];