/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Finance {
    title: string;
    date: string;
    createdAt: bigint;
    recurring: boolean;
    financeType: FinanceType;
    description: string;
    author: Principal;
    updatedAt: bigint;
    financeId: FinanceId;
    amount: bigint;
    purpose: string;
}
export type Year = bigint;
export type ReminderId = bigint;
export type Language = {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "portuguese";
    portuguese: null;
} | {
    __kind__: "japanese";
    japanese: null;
} | {
    __kind__: "chinese";
    chinese: null;
} | {
    __kind__: "italian";
    italian: null;
} | {
    __kind__: "spanish";
    spanish: null;
} | {
    __kind__: "german";
    german: null;
} | {
    __kind__: "arabic";
    arabic: null;
} | {
    __kind__: "french";
    french: null;
} | {
    __kind__: "russian";
    russian: null;
} | {
    __kind__: "dutch";
    dutch: null;
} | {
    __kind__: "english";
    english: null;
} | {
    __kind__: "korean";
    korean: null;
};
export interface Habit {
    isCompleted: boolean;
    date: string;
    name: string;
    createdAt: bigint;
    description: string;
    habitId: HabitId;
    author: Principal;
    updatedAt: bigint;
}
export type Month = bigint;
export type JournalId = bigint;
export type GoalType = {
    __kind__: "habit";
    habit: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "monthly";
    monthly: null;
} | {
    __kind__: "yearly";
    yearly: null;
} | {
    __kind__: "daily";
    daily: null;
} | {
    __kind__: "project";
    project: null;
} | {
    __kind__: "weekly";
    weekly: null;
};
export interface Activity {
    startTime?: string;
    duration?: bigint;
    endTime?: string;
    goalType: GoalType;
    date: string;
    name: string;
    createdAt: bigint;
    recurring: boolean;
    activityId: ActivityId;
    description: string;
    author: Principal;
    coverImage?: string;
    updatedAt: bigint;
    colorHex?: string;
}
export interface Reminder {
    reminderId: ReminderId;
    name: string;
    createdAt: bigint;
    description: string;
    repeatSchema?: string;
    author: Principal;
    updatedAt: bigint;
    colorHex?: string;
    targetDate: string;
}
export interface Journal {
    title: string;
    content: string;
    date: string;
    createdAt: bigint;
    journalId: JournalId;
    locked: boolean;
    accessType: JournalAccessType;
    author: Principal;
    sharedWith?: Array<string>;
    entropy: bigint;
    coverImage?: string;
    updatedAt: bigint;
    colorHex?: string;
    hasAttachments: boolean;
}
export type FinanceId = bigint;
export type HabitId = bigint;
export type ActivityId = bigint;
export type Theme = {
    __kind__: "red";
    red: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "blue";
    blue: null;
} | {
    __kind__: "dark";
    dark: null;
} | {
    __kind__: "purple";
    purple: null;
} | {
    __kind__: "light";
    light: null;
} | {
    __kind__: "green";
    green: null;
} | {
    __kind__: "yellow";
    yellow: null;
};
export interface UserProfile {
    theme: Theme;
    username: string;
    createdAt: bigint;
    email?: string;
    language: Language;
    updatedAt: bigint;
}
export enum FinanceType {
    expense = "expense",
    investment = "investment",
    income = "income"
}
export enum JournalAccessType {
    public_journal_access = "public_journal_access",
    private_journal_access = "private_journal_access"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calendar(month: Month, year: Year): Promise<string>;
    care(): Promise<boolean>;
    createActivity(activity: Activity): Promise<ActivityId>;
    createFinance(finance: Finance): Promise<FinanceId>;
    createHabit(habit: Habit): Promise<HabitId>;
    createJournal(journal: Journal): Promise<JournalId>;
    createReminder(reminder: Reminder): Promise<ReminderId>;
    deleteActivity(activityId: ActivityId): Promise<void>;
    deleteFinance(financeId: FinanceId): Promise<void>;
    deleteHabit(habitId: HabitId): Promise<void>;
    deleteJournal(journalId: JournalId): Promise<void>;
    deleteReminder(reminderId: ReminderId): Promise<void>;
    getActivitiesByDate(date: string): Promise<Array<Activity>>;
    getActivity(activityId: ActivityId): Promise<Activity>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFinancesByDate(date: string): Promise<Array<Finance>>;
    getHabitsByDate(date: string): Promise<Array<Habit>>;
    getJournalByDate(date: string): Promise<Journal | null>;
    getRemindersByDate(date: string): Promise<Array<Reminder>>;
    getSetupStatus(): Promise<boolean>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<UserProfile>;
    updateActivity(activityId: ActivityId, activity: Activity): Promise<void>;
    updateHabit(habitId: HabitId, habit: Habit): Promise<void>;
    updateJournal(journalId: JournalId, journal: Journal): Promise<void>;
    week(): Promise<[Array<string>, boolean, string]>;
}
import type { Activity as _Activity, ActivityId as _ActivityId, Finance as _Finance, FinanceId as _FinanceId, FinanceType as _FinanceType, GoalType as _GoalType, Journal as _Journal, JournalAccessType as _JournalAccessType, JournalId as _JournalId, Language as _Language, Reminder as _Reminder, ReminderId as _ReminderId, Theme as _Theme, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calendar(arg0: Month, arg1: Year): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.calendar(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calendar(arg0, arg1);
            return result;
        }
    }
    async care(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.care();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.care();
            return result;
        }
    }
    async createActivity(arg0: Activity): Promise<ActivityId> {
        if (this.processError) {
            try {
                const result = await this.actor.createActivity(to_candid_Activity_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createActivity(to_candid_Activity_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createFinance(arg0: Finance): Promise<FinanceId> {
        if (this.processError) {
            try {
                const result = await this.actor.createFinance(to_candid_Finance_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFinance(to_candid_Finance_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createHabit(arg0: Habit): Promise<HabitId> {
        if (this.processError) {
            try {
                const result = await this.actor.createHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHabit(arg0);
            return result;
        }
    }
    async createJournal(arg0: Journal): Promise<JournalId> {
        if (this.processError) {
            try {
                const result = await this.actor.createJournal(to_candid_Journal_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJournal(to_candid_Journal_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createReminder(arg0: Reminder): Promise<ReminderId> {
        if (this.processError) {
            try {
                const result = await this.actor.createReminder(to_candid_Reminder_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReminder(to_candid_Reminder_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteActivity(arg0: ActivityId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteActivity(arg0);
            return result;
        }
    }
    async deleteFinance(arg0: FinanceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFinance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFinance(arg0);
            return result;
        }
    }
    async deleteHabit(arg0: HabitId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHabit(arg0);
            return result;
        }
    }
    async deleteJournal(arg0: JournalId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournal(arg0);
            return result;
        }
    }
    async deleteReminder(arg0: ReminderId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReminder(arg0);
            return result;
        }
    }
    async getActivitiesByDate(arg0: string): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivitiesByDate(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivitiesByDate(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivity(arg0: ActivityId): Promise<Activity> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivity(arg0);
                return from_candid_Activity_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivity(arg0);
            return from_candid_Activity_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinancesByDate(arg0: string): Promise<Array<Finance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancesByDate(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancesByDate(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHabitsByDate(arg0: string): Promise<Array<Habit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabitsByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabitsByDate(arg0);
            return result;
        }
    }
    async getJournalByDate(arg0: string): Promise<Journal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalByDate(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalByDate(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRemindersByDate(arg0: string): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemindersByDate(arg0);
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemindersByDate(arg0);
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSetupStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getSetupStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSetupStatus();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfile_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfile_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateActivity(arg0: ActivityId, arg1: Activity): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivity(arg0, to_candid_Activity_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivity(arg0, to_candid_Activity_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateHabit(arg0: HabitId, arg1: Habit): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHabit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHabit(arg0, arg1);
            return result;
        }
    }
    async updateJournal(arg0: JournalId, arg1: Journal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJournal(arg0, to_candid_Journal_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJournal(arg0, to_candid_Journal_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async week(): Promise<[Array<string>, boolean, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.week();
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.week();
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
}
function from_candid_Activity_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_FinanceType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinanceType): FinanceType {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Finance_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Finance): Finance {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_GoalType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalType): GoalType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_JournalAccessType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JournalAccessType): JournalAccessType {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Journal_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Journal): Journal {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Reminder_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reminder): Reminder {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Theme_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Theme): Theme {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Journal]): Journal | null {
    return value.length === 0 ? null : from_candid_Journal_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: [] | [string];
    duration: [] | [bigint];
    endTime: [] | [string];
    goalType: _GoalType;
    date: string;
    name: string;
    createdAt: bigint;
    recurring: boolean;
    activityId: _ActivityId;
    description: string;
    author: Principal;
    coverImage: [] | [string];
    updatedAt: bigint;
    colorHex: [] | [string];
}): {
    startTime?: string;
    duration?: bigint;
    endTime?: string;
    goalType: GoalType;
    date: string;
    name: string;
    createdAt: bigint;
    recurring: boolean;
    activityId: ActivityId;
    description: string;
    author: Principal;
    coverImage?: string;
    updatedAt: bigint;
    colorHex?: string;
} {
    return {
        startTime: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.startTime)),
        duration: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.duration)),
        endTime: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.endTime)),
        goalType: from_candid_GoalType_n22(_uploadFile, _downloadFile, value.goalType),
        date: value.date,
        name: value.name,
        createdAt: value.createdAt,
        recurring: value.recurring,
        activityId: value.activityId,
        description: value.description,
        author: value.author,
        coverImage: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.coverImage)),
        updatedAt: value.updatedAt,
        colorHex: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.colorHex))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: _Theme;
    username: string;
    createdAt: bigint;
    email: [] | [string];
    language: _Language;
    updatedAt: bigint;
}): {
    theme: Theme;
    username: string;
    createdAt: bigint;
    email?: string;
    language: Language;
    updatedAt: bigint;
} {
    return {
        theme: from_candid_Theme_n27(_uploadFile, _downloadFile, value.theme),
        username: value.username,
        createdAt: value.createdAt,
        email: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.email)),
        language: from_candid_Language_n29(_uploadFile, _downloadFile, value.language),
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: string;
    createdAt: bigint;
    recurring: boolean;
    financeType: _FinanceType;
    description: string;
    author: Principal;
    updatedAt: bigint;
    financeId: _FinanceId;
    amount: bigint;
    purpose: string;
}): {
    title: string;
    date: string;
    createdAt: bigint;
    recurring: boolean;
    financeType: FinanceType;
    description: string;
    author: Principal;
    updatedAt: bigint;
    financeId: FinanceId;
    amount: bigint;
    purpose: string;
} {
    return {
        title: value.title,
        date: value.date,
        createdAt: value.createdAt,
        recurring: value.recurring,
        financeType: from_candid_FinanceType_n36(_uploadFile, _downloadFile, value.financeType),
        description: value.description,
        author: value.author,
        updatedAt: value.updatedAt,
        financeId: value.financeId,
        amount: value.amount,
        purpose: value.purpose
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    date: string;
    createdAt: bigint;
    journalId: _JournalId;
    locked: boolean;
    accessType: _JournalAccessType;
    author: Principal;
    sharedWith: [] | [Array<string>];
    entropy: bigint;
    coverImage: [] | [string];
    updatedAt: bigint;
    colorHex: [] | [string];
    hasAttachments: boolean;
}): {
    title: string;
    content: string;
    date: string;
    createdAt: bigint;
    journalId: JournalId;
    locked: boolean;
    accessType: JournalAccessType;
    author: Principal;
    sharedWith?: Array<string>;
    entropy: bigint;
    coverImage?: string;
    updatedAt: bigint;
    colorHex?: string;
    hasAttachments: boolean;
} {
    return {
        title: value.title,
        content: value.content,
        date: value.date,
        createdAt: value.createdAt,
        journalId: value.journalId,
        locked: value.locked,
        accessType: from_candid_JournalAccessType_n41(_uploadFile, _downloadFile, value.accessType),
        author: value.author,
        sharedWith: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.sharedWith)),
        entropy: value.entropy,
        coverImage: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.coverImage)),
        updatedAt: value.updatedAt,
        colorHex: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.colorHex)),
        hasAttachments: value.hasAttachments
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reminderId: _ReminderId;
    name: string;
    createdAt: bigint;
    description: string;
    repeatSchema: [] | [string];
    author: Principal;
    updatedAt: bigint;
    colorHex: [] | [string];
    targetDate: string;
}): {
    reminderId: ReminderId;
    name: string;
    createdAt: bigint;
    description: string;
    repeatSchema?: string;
    author: Principal;
    updatedAt: bigint;
    colorHex?: string;
    targetDate: string;
} {
    return {
        reminderId: value.reminderId,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        repeatSchema: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.repeatSchema)),
        author: value.author,
        updatedAt: value.updatedAt,
        colorHex: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.colorHex)),
        targetDate: value.targetDate
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    habit: null;
} | {
    custom: string;
} | {
    monthly: null;
} | {
    yearly: null;
} | {
    daily: null;
} | {
    project: null;
} | {
    weekly: null;
}): {
    __kind__: "habit";
    habit: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "monthly";
    monthly: null;
} | {
    __kind__: "yearly";
    yearly: null;
} | {
    __kind__: "daily";
    daily: null;
} | {
    __kind__: "project";
    project: null;
} | {
    __kind__: "weekly";
    weekly: null;
} {
    return "habit" in value ? {
        __kind__: "habit",
        habit: value.habit
    } : "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "monthly" in value ? {
        __kind__: "monthly",
        monthly: value.monthly
    } : "yearly" in value ? {
        __kind__: "yearly",
        yearly: value.yearly
    } : "daily" in value ? {
        __kind__: "daily",
        daily: value.daily
    } : "project" in value ? {
        __kind__: "project",
        project: value.project
    } : "weekly" in value ? {
        __kind__: "weekly",
        weekly: value.weekly
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    custom: string;
} | {
    blue: null;
} | {
    dark: null;
} | {
    purple: null;
} | {
    light: null;
} | {
    green: null;
} | {
    yellow: null;
}): {
    __kind__: "red";
    red: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "blue";
    blue: null;
} | {
    __kind__: "dark";
    dark: null;
} | {
    __kind__: "purple";
    purple: null;
} | {
    __kind__: "light";
    light: null;
} | {
    __kind__: "green";
    green: null;
} | {
    __kind__: "yellow";
    yellow: null;
} {
    return "red" in value ? {
        __kind__: "red",
        red: value.red
    } : "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "blue" in value ? {
        __kind__: "blue",
        blue: value.blue
    } : "dark" in value ? {
        __kind__: "dark",
        dark: value.dark
    } : "purple" in value ? {
        __kind__: "purple",
        purple: value.purple
    } : "light" in value ? {
        __kind__: "light",
        light: value.light
    } : "green" in value ? {
        __kind__: "green",
        green: value.green
    } : "yellow" in value ? {
        __kind__: "yellow",
        yellow: value.yellow
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: string;
} | {
    portuguese: null;
} | {
    japanese: null;
} | {
    chinese: null;
} | {
    italian: null;
} | {
    spanish: null;
} | {
    german: null;
} | {
    arabic: null;
} | {
    french: null;
} | {
    russian: null;
} | {
    dutch: null;
} | {
    english: null;
} | {
    korean: null;
}): {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "portuguese";
    portuguese: null;
} | {
    __kind__: "japanese";
    japanese: null;
} | {
    __kind__: "chinese";
    chinese: null;
} | {
    __kind__: "italian";
    italian: null;
} | {
    __kind__: "spanish";
    spanish: null;
} | {
    __kind__: "german";
    german: null;
} | {
    __kind__: "arabic";
    arabic: null;
} | {
    __kind__: "french";
    french: null;
} | {
    __kind__: "russian";
    russian: null;
} | {
    __kind__: "dutch";
    dutch: null;
} | {
    __kind__: "english";
    english: null;
} | {
    __kind__: "korean";
    korean: null;
} {
    return "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "portuguese" in value ? {
        __kind__: "portuguese",
        portuguese: value.portuguese
    } : "japanese" in value ? {
        __kind__: "japanese",
        japanese: value.japanese
    } : "chinese" in value ? {
        __kind__: "chinese",
        chinese: value.chinese
    } : "italian" in value ? {
        __kind__: "italian",
        italian: value.italian
    } : "spanish" in value ? {
        __kind__: "spanish",
        spanish: value.spanish
    } : "german" in value ? {
        __kind__: "german",
        german: value.german
    } : "arabic" in value ? {
        __kind__: "arabic",
        arabic: value.arabic
    } : "french" in value ? {
        __kind__: "french",
        french: value.french
    } : "russian" in value ? {
        __kind__: "russian",
        russian: value.russian
    } : "dutch" in value ? {
        __kind__: "dutch",
        dutch: value.dutch
    } : "english" in value ? {
        __kind__: "english",
        english: value.english
    } : "korean" in value ? {
        __kind__: "korean",
        korean: value.korean
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expense: null;
} | {
    investment: null;
} | {
    income: null;
}): FinanceType {
    return "expense" in value ? FinanceType.expense : "investment" in value ? FinanceType.investment : "income" in value ? FinanceType.income : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    public_journal_access: null;
} | {
    private_journal_access: null;
}): JournalAccessType {
    return "public_journal_access" in value ? JournalAccessType.public_journal_access : "private_journal_access" in value ? JournalAccessType.private_journal_access : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Finance>): Array<Finance> {
    return value.map((x)=>from_candid_Finance_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reminder>): Array<Reminder> {
    return value.map((x)=>from_candid_Reminder_n45(_uploadFile, _downloadFile, x));
}
function to_candid_Activity_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Activity): _Activity {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_FinanceType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FinanceType): _FinanceType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Finance_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Finance): _Finance {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_GoalType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalType): _GoalType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_JournalAccessType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JournalAccessType): _JournalAccessType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Journal_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Journal): _Journal {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Language_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_Reminder_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Reminder): _Reminder {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Theme_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Theme): _Theme {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    date: string;
    createdAt: bigint;
    journalId: JournalId;
    locked: boolean;
    accessType: JournalAccessType;
    author: Principal;
    sharedWith?: Array<string>;
    entropy: bigint;
    coverImage?: string;
    updatedAt: bigint;
    colorHex?: string;
    hasAttachments: boolean;
}): {
    title: string;
    content: string;
    date: string;
    createdAt: bigint;
    journalId: _JournalId;
    locked: boolean;
    accessType: _JournalAccessType;
    author: Principal;
    sharedWith: [] | [Array<string>];
    entropy: bigint;
    coverImage: [] | [string];
    updatedAt: bigint;
    colorHex: [] | [string];
    hasAttachments: boolean;
} {
    return {
        title: value.title,
        content: value.content,
        date: value.date,
        createdAt: value.createdAt,
        journalId: value.journalId,
        locked: value.locked,
        accessType: to_candid_JournalAccessType_n13(_uploadFile, _downloadFile, value.accessType),
        author: value.author,
        sharedWith: value.sharedWith ? candid_some(value.sharedWith) : candid_none(),
        entropy: value.entropy,
        coverImage: value.coverImage ? candid_some(value.coverImage) : candid_none(),
        updatedAt: value.updatedAt,
        colorHex: value.colorHex ? candid_some(value.colorHex) : candid_none(),
        hasAttachments: value.hasAttachments
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reminderId: ReminderId;
    name: string;
    createdAt: bigint;
    description: string;
    repeatSchema?: string;
    author: Principal;
    updatedAt: bigint;
    colorHex?: string;
    targetDate: string;
}): {
    reminderId: _ReminderId;
    name: string;
    createdAt: bigint;
    description: string;
    repeatSchema: [] | [string];
    author: Principal;
    updatedAt: bigint;
    colorHex: [] | [string];
    targetDate: string;
} {
    return {
        reminderId: value.reminderId,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        repeatSchema: value.repeatSchema ? candid_some(value.repeatSchema) : candid_none(),
        author: value.author,
        updatedAt: value.updatedAt,
        colorHex: value.colorHex ? candid_some(value.colorHex) : candid_none(),
        targetDate: value.targetDate
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime?: string;
    duration?: bigint;
    endTime?: string;
    goalType: GoalType;
    date: string;
    name: string;
    createdAt: bigint;
    recurring: boolean;
    activityId: ActivityId;
    description: string;
    author: Principal;
    coverImage?: string;
    updatedAt: bigint;
    colorHex?: string;
}): {
    startTime: [] | [string];
    duration: [] | [bigint];
    endTime: [] | [string];
    goalType: _GoalType;
    date: string;
    name: string;
    createdAt: bigint;
    recurring: boolean;
    activityId: _ActivityId;
    description: string;
    author: Principal;
    coverImage: [] | [string];
    updatedAt: bigint;
    colorHex: [] | [string];
} {
    return {
        startTime: value.startTime ? candid_some(value.startTime) : candid_none(),
        duration: value.duration ? candid_some(value.duration) : candid_none(),
        endTime: value.endTime ? candid_some(value.endTime) : candid_none(),
        goalType: to_candid_GoalType_n5(_uploadFile, _downloadFile, value.goalType),
        date: value.date,
        name: value.name,
        createdAt: value.createdAt,
        recurring: value.recurring,
        activityId: value.activityId,
        description: value.description,
        author: value.author,
        coverImage: value.coverImage ? candid_some(value.coverImage) : candid_none(),
        updatedAt: value.updatedAt,
        colorHex: value.colorHex ? candid_some(value.colorHex) : candid_none()
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: Theme;
    username: string;
    createdAt: bigint;
    email?: string;
    language: Language;
    updatedAt: bigint;
}): {
    theme: _Theme;
    username: string;
    createdAt: bigint;
    email: [] | [string];
    language: _Language;
    updatedAt: bigint;
} {
    return {
        theme: to_candid_Theme_n49(_uploadFile, _downloadFile, value.theme),
        username: value.username,
        createdAt: value.createdAt,
        email: value.email ? candid_some(value.email) : candid_none(),
        language: to_candid_Language_n51(_uploadFile, _downloadFile, value.language),
        updatedAt: value.updatedAt
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: string;
    createdAt: bigint;
    recurring: boolean;
    financeType: FinanceType;
    description: string;
    author: Principal;
    updatedAt: bigint;
    financeId: FinanceId;
    amount: bigint;
    purpose: string;
}): {
    title: string;
    date: string;
    createdAt: bigint;
    recurring: boolean;
    financeType: _FinanceType;
    description: string;
    author: Principal;
    updatedAt: bigint;
    financeId: _FinanceId;
    amount: bigint;
    purpose: string;
} {
    return {
        title: value.title,
        date: value.date,
        createdAt: value.createdAt,
        recurring: value.recurring,
        financeType: to_candid_FinanceType_n9(_uploadFile, _downloadFile, value.financeType),
        description: value.description,
        author: value.author,
        updatedAt: value.updatedAt,
        financeId: value.financeId,
        amount: value.amount,
        purpose: value.purpose
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FinanceType): {
    expense: null;
} | {
    investment: null;
} | {
    income: null;
} {
    return value == FinanceType.expense ? {
        expense: null
    } : value == FinanceType.investment ? {
        investment: null
    } : value == FinanceType.income ? {
        income: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JournalAccessType): {
    public_journal_access: null;
} | {
    private_journal_access: null;
} {
    return value == JournalAccessType.public_journal_access ? {
        public_journal_access: null
    } : value == JournalAccessType.private_journal_access ? {
        private_journal_access: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "red";
    red: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "blue";
    blue: null;
} | {
    __kind__: "dark";
    dark: null;
} | {
    __kind__: "purple";
    purple: null;
} | {
    __kind__: "light";
    light: null;
} | {
    __kind__: "green";
    green: null;
} | {
    __kind__: "yellow";
    yellow: null;
}): {
    red: null;
} | {
    custom: string;
} | {
    blue: null;
} | {
    dark: null;
} | {
    purple: null;
} | {
    light: null;
} | {
    green: null;
} | {
    yellow: null;
} {
    return value.__kind__ === "red" ? {
        red: value.red
    } : value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "blue" ? {
        blue: value.blue
    } : value.__kind__ === "dark" ? {
        dark: value.dark
    } : value.__kind__ === "purple" ? {
        purple: value.purple
    } : value.__kind__ === "light" ? {
        light: value.light
    } : value.__kind__ === "green" ? {
        green: value.green
    } : value.__kind__ === "yellow" ? {
        yellow: value.yellow
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "portuguese";
    portuguese: null;
} | {
    __kind__: "japanese";
    japanese: null;
} | {
    __kind__: "chinese";
    chinese: null;
} | {
    __kind__: "italian";
    italian: null;
} | {
    __kind__: "spanish";
    spanish: null;
} | {
    __kind__: "german";
    german: null;
} | {
    __kind__: "arabic";
    arabic: null;
} | {
    __kind__: "french";
    french: null;
} | {
    __kind__: "russian";
    russian: null;
} | {
    __kind__: "dutch";
    dutch: null;
} | {
    __kind__: "english";
    english: null;
} | {
    __kind__: "korean";
    korean: null;
}): {
    custom: string;
} | {
    portuguese: null;
} | {
    japanese: null;
} | {
    chinese: null;
} | {
    italian: null;
} | {
    spanish: null;
} | {
    german: null;
} | {
    arabic: null;
} | {
    french: null;
} | {
    russian: null;
} | {
    dutch: null;
} | {
    english: null;
} | {
    korean: null;
} {
    return value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "portuguese" ? {
        portuguese: value.portuguese
    } : value.__kind__ === "japanese" ? {
        japanese: value.japanese
    } : value.__kind__ === "chinese" ? {
        chinese: value.chinese
    } : value.__kind__ === "italian" ? {
        italian: value.italian
    } : value.__kind__ === "spanish" ? {
        spanish: value.spanish
    } : value.__kind__ === "german" ? {
        german: value.german
    } : value.__kind__ === "arabic" ? {
        arabic: value.arabic
    } : value.__kind__ === "french" ? {
        french: value.french
    } : value.__kind__ === "russian" ? {
        russian: value.russian
    } : value.__kind__ === "dutch" ? {
        dutch: value.dutch
    } : value.__kind__ === "english" ? {
        english: value.english
    } : value.__kind__ === "korean" ? {
        korean: value.korean
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "habit";
    habit: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "monthly";
    monthly: null;
} | {
    __kind__: "yearly";
    yearly: null;
} | {
    __kind__: "daily";
    daily: null;
} | {
    __kind__: "project";
    project: null;
} | {
    __kind__: "weekly";
    weekly: null;
}): {
    habit: null;
} | {
    custom: string;
} | {
    monthly: null;
} | {
    yearly: null;
} | {
    daily: null;
} | {
    project: null;
} | {
    weekly: null;
} {
    return value.__kind__ === "habit" ? {
        habit: value.habit
    } : value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "monthly" ? {
        monthly: value.monthly
    } : value.__kind__ === "yearly" ? {
        yearly: value.yearly
    } : value.__kind__ === "daily" ? {
        daily: value.daily
    } : value.__kind__ === "project" ? {
        project: value.project
    } : value.__kind__ === "weekly" ? {
        weekly: value.weekly
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
